// Articles
export const GET_ARTICLES_SUCCESS = 'GET_ARTICLES_SUCCESS';

// Widgets
export const GET_WIDGETS_SUCCESS = 'GET_WIDGETS_SUCCESS';
export const DELETE_WIDGET_SUCCESS = 'DELETE_WIDGET_SUCCESS';

// Search Layout
export const LOAD_SEARCH_LAYOUT = 'LOAD_SEARCH_LAYOUT';

// User
export const GET_PROFILE_SUCCESS = 'GET_PROFILE_SUCCESS';

// Rubrics
export const GET_RUBRICS_SUCCESS = 'GET_RUBRICS_SUCCESS';
